export const SearchActionTypes = {
    SEARCH_RECIPES_START: "SEARCH_RECIPES_START",
    SEARCH_RECIPES_SUCCESSFUL: "SEARCH_RECIPES_SUCCESSFUL",
    SEARCH_RECIPES_FAILURE: "SEARCH_RECIPES_FAILURE",
    SET_SEARCH_TO_OFF:"SET_SEARCH_TO_OFF"
}

export default SearchActionTypes;