const RecipesActionTypes = {
    ADD_RECIPE_START: 'ADD_RECIPE_START',
    ADD_RECIPE_SUCCESSFUL: 'ADD_RECIPE_SUCCESSFUL',
    ADD_RECIPE_FAILURE: 'ADD_RECIPE_FAILURE',
    UPDATE_RECIPES_START: "UPDATE_RECIPES_START",
    UPDATE_RECIPES_SUCCESSFUL: "UPDATE_RECIPES_SUCCESSFUL",
    UPDATE_RECIPES_FAILURE: "UPDATE_RECIPES_FAILURE",
    POST_COMMENT_START: "POST_COMMENT_START",
    POST_COMMENT_SUCCESSFUL: "POST_COMMENT_SUCCESSFUL",
    POST_COMMENT_FAILURE: "POST_COMMENT_FAILURE",
    GET_RECIPE_COMMENTS_START: "GET_RECIPE_COMMENTS_START",
    GET_RECIPE_COMMENTS_SUCCESSFUL: "GET_RECIPE_COMMENTS_SUCCESSFUL",
    GET_RECIPE_COMMENTS_FAILURE: "GET_RECIPE_COMMENTS_FAILURE",
    DELETE_COMMENT_START: "DELETE_COMMENT_START",
    DELETE_COMMENT_SUCCESSFUL: "DELETE_COMMENT_SUCCESSFUL",
    DELETE_COMMENT_FAILURE: "DELETE_COMMENT_FAILURE",
}

export default RecipesActionTypes;