const RecipesActionTypes = {
    UPDATE_RECIPES: "UPDATE_RECIPES",
    UPDATE_RECIPES_START: "UPDATE_RECIPES_START",
    UPDATE_RECIPES_SUCCESSFUL: "UPDATE_RECIPES_SUCCESSFUL",
    UPDATE_RECIPES_FAILURE: "UPDATE_RECIPES_FAILURE"
}

export default RecipesActionTypes;