export const RecommenderActionTypes = {
    ALL_TIME_SEARCH_START: "ALL_TIME_SEARCH_START",
    ALL_TIME_SEARCH_SUCCESSFUL: "ALL_TIME_SEARCH_SUCCESSFUL",
    ALL_TIME_SEARCH_FAILURE: "ALL_TIME_SEARCH_FAILURE",
    RECENTS_SEARCH_START: "RECENTS_SEARCH_START",
    RECENTS_SEARCH_SUCCESSFUL: "RECENTS_SEARCH_SUCCESSFUL",
    RECENTS_SEARCH_FAILURE: "RECENTS_SEARCH_FAILURE",
}

export default RecommenderActionTypes;