export const RecommenderActionTypes = {
    RECOMMENDER_SEARCH_START: "RECOMMENDER_SEARCH_START",
    RECOMMENDER_SEARCH_SUCCESSFUL: "RECOMMENDER_SEARCH_SUCCESSFUL",
    RECOMMENDER_SEARCH_FAILURE: "RECOMMENDER_SEARCH_FAILURE",
}

export default RecommenderActionTypes;