export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  ADD_USER_HISTORY_START: 'ADD_USER_HISTORY_START',
  ADD_USER_HISTORY_SUCCESSFUL: 'ADD_USER_HISTORY_SUCCESSFUL',
  ADD_USER_HISTORY_FAIL: 'ADD_USER_HISTORY_FAIL',
  SET_MEAL_PLAN_START: 'SET_MEAL_PLAN_START',
  SET_MEAL_PLAN_SUCCESS: 'SET_MEAL_PLAN_SUCCESS',
  SET_MEAL_PLAN_FAIL: 'SET_MEAL_PLAN_FAIL',
  GET_USER_COMMENTS_START: "GET_COMMENTS_START",
  GET_USER_COMMENTS_SUCCESSFUL: "GET_COMMENTS_SUCCESSFUL",
  GET_USER_COMMENTS_FAILURE: "GET_COMMENTS_FAILURE"
};
