export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  ADD_USER_HISTORY_START: 'ADD_USER_HISTORY_START',
  ADD_USER_HISTORY_SUCCESSFUL: 'ADD_USER_HISTORY_SUCCESSFUL',
  ADD_USER_HISTORY_FAIL: 'ADD_USER_HISTORY_FAIL'
};
